version: "3"

services:
  render:
    volumes: []

  webapp:
    build:
      args:
        - NODE_ENV=production
    volumes: []
    # entrypoint: ["serve"]
    # command: ["dist", "-l", "${WEB_CLIENT_PORT}"]
    env_file: ./webapp/.env.production
  nginx:
    build: ./nginx
    ports:
      - ${REVERSE_PROXY_PORT}:${REVERSE_PROXY_PORT}

    depends_on:
      - webapp
