version: "3"

services:
  # postgres:
  #   build: ./postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres:/var/lib/postgres
  #     - postgres_binary:/var/lib/postgres_binary
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_DB: borehole_database
  #   restart: always

  # rest:
  #   build: ./rest
  #   ports:
  #     - 5001:5001
  #   volumes:
  #     - ./rest:/app # for development - not neccessary for production
  #     - postgres_binary:/var/lib/postgres_binary
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_DB: borehole_database
  #     POSTGRES_PORT: 5432
  #     POSTGRES_HOST: postgres
  #   restart: always
  #   depends_on:
  #     - postgres

  render:
    build: ./render
    volumes:
      - ./render:/opt/paraview/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - $RENDER_SERVER_PORT:$RENDER_SERVER_PORT
    restart: always

  webapp:
    build: ./webapp
    ports:
      - ${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}
    environment:
      - RENDER_SERVER_PORT=${RENDER_SERVER_PORT}
      - VUE_APP_RENDER_SERVER_PORT=${RENDER_SERVER_PORT}
    env_file:
      - ./webapp/.env.development
    volumes:
      - ./webapp/src:/app/src
    entrypoint: ["yarn", "serve"]
    command: ["--port", "${WEB_CLIENT_PORT}"]
    restart: always
    depends_on:
      - render

  sandbox:
    build: ./sandbox
# volumes:
#   postgres:
#     driver: local
#   postgres_binary:
#     driver: local
