version: '3'

services:
  postgres:
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres
      - ./_common:/_common
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: borehole_database
    restart: always

  rest:
    build: ./rest
    ports:
      - 5001:5001
    volumes:
      - ./rest:/app # for debug mode - not neccessary for production
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: borehole_database
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    restart: always
    depends_on:
        - postgres

volumes:
  postgres:
    driver: local
