version: "3"

services:
  # postgres:
  #   build: ./postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres:/var/lib/postgres
  #     - postgres_binary:/var/lib/postgres_binary
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_DB: borehole_database
  #   restart: always

  # rest:
  #   build: ./rest
  #   ports:
  #     - 5001:5001
  #   volumes:
  #     - ./rest:/app # for development - not neccessary for production
  #     - postgres_binary:/var/lib/postgres_binary
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_DB: borehole_database
  #     POSTGRES_PORT: 5432
  #     POSTGRES_HOST: postgres
  #   restart: always
  #   depends_on:
  #     - postgres

  paraview:
    build: ./paraview
    volumes:
      - ./paraview:/opt/paraview/app
    ports:
      - $RENDER_SERVER_PORT:$RENDER_SERVER_PORT
    restart: always

  webapp:
    build: ./webapp
    ports:
      - ${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}
    environment:
      - RENDER_SERVER_PORT=${RENDER_SERVER_PORT}
    env_file:
      - "dev.env"
    volumes:
      - ./webapp/src:/app/src
    command: yarn serve --port ${WEB_CLIENT_PORT}
    restart: always
    depends_on:
      - paraview

  sandbox:
    build: ./sandbox
# volumes:
#   postgres:
#     driver: local
#   postgres_binary:
#     driver: local
